### ISSUE TITLE
Nothing happens when I press translate

### ISSUE THREAD

**Issue by ghost** [KryptoST/SRTranslatorGUI#10]
Hi. I do not know anything about coding stuff and when I searched, I saw that I needed Visual Studio to open .sln files. I managed to get the app to open using Visual Studio and chose my .srt file, but when I selected language (from en to tr) it just says translating and nothing more. 

Additionally I had a warning in Visual Studio; MSB3821: Couldn't process file [file] due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.

Is is stuck in translating because of this warning? How to proceed from here? I saw you said use Firefox to someone else. I could not get it to work there either. Please help. Thank you.

**Comment by KryptoST** [comment]
If you are using the version
1.x need to have
https://github.com/sinedie/SRTranslator
Firefox
2.x
Firefox

**Comment by ghost** [comment]
> If you are using the version 1.x need to have https://github.com/sinedie/SRTranslator Firefox 2.x Firefox

Thank you so much.
