### ISSUE TITLE
Failed error.

### ISSUE THREAD

**Issue by ghost** [KryptoST/SRTranslatorGUI#12]
When I try to translate, I get "failed" error. I tried Turkish and German languages, and they both failed. I am trying it from English to Turkish. I am using Deep Scrapt as the translator.

![fsg](https://github.com/KryptoST/SRTranslatorGUI/assets/141356815/f760e3da-c3fd-44dd-b9ac-25ad682b5b26)

**Comment by KryptoST** [comment]
Which version are you using?

**Comment by ghost** [comment]
I was using 2.0.4b normally, but tried 2.0.3b and 2.0.5b to see if it'll work, but it didn't. I used 2.0.4b without a problem for 3 weeks.

**Comment by KryptoST** [comment]
I just reuploaded version 2.0.5b, I don't know what happens I'll see later but it's already working

**Comment by ghost** [comment]
Okay, I will try again and let you know. Thank you.

**Comment by ghost** [comment]
At first, the new upload did not work as well, but this time the command panel opened. So I tired deleting rust_mozprofile folders inside  of "C:\Users\username\AppData\Local\Temp", and it started working. Thank you for your help.
