### ISSUE TITLE
Unreliable Behaviour

### ISSUE THREAD

**Issue by KevinSierraRojas** [KryptoST/SRTranslatorGUI#14]
I've been usign version 2.x of the GUI. 

The last time I use this tool (August) it was working pretty well, most of the erros I got then were caused by some characters that aren't well process by DeepL, but recently I'm getting a lot of errors trying to translate any file. 

I have to point out that the files DO get translated but only after a lot of trials (>8 for some files).  This happens for different configurations of the GUI (ENG -> ESP, JAP -> ENG, JAP  -> ESP) and on v2.0.5b and v2.0.4b. 

When I check the "SHOWBROWSER" option, the DeepL page appears but (most of the time) nothing else happens. 

[image](https://github.com/KryptoST/SRTranslatorGUI/assets/129124101/aeb189cd-1332-47cd-8d45-4a6d342d9fc8)

Not even the configurations starts, for example if I set the GUI to translate from English to Spanish, DeepL keeps the predefined configuration. At the end I just get the same "Translation Timed out" error.

![image](https://github.com/KryptoST/SRTranslatorGUI/assets/129124101/c432922a-c0d2-421d-a56e-989940031ecf)

Since it was working on august, I might be wrong, but maybe it has to be with Firefox version that was updated at the end of september (currently 118.0.1). 

If so... What is the Firefox version (or its configuration) that is actually compatible with the current GUI?

**Comment by ghost** [comment]
I am also having this same problem, and another friend of mine has it too. It sometimes takes several tries to get it to work just like yours, and when it works, there are untranslated blank lines sometimes.

**Comment by KevinSierraRojas** [comment]
Well, I tried some older versions of Firefoz Mozilla but the performance was the same.
It would be nice if the GUI could automatically restart the process when this specific problem appears, in order to reliably get some output when translating files.

**Comment by KevinSierraRojas** [comment]
Now it isn't translating at all... no matter how many trials.

(Something odd) Instead it generates large Temp files, after each unsuccesfull trial.

**Comment by ghost** [comment]
> Now it isn't translating at all... no matter how many trials.
> 
> (Something odd) Instead it generates large Temp files, after each unsuccesfull trial.

Yes, I also opened an issue regarding this problem. sinedie uploaded a new release, maybe this will be updated too.
