### ISSUE TITLE
"Translation timed out" on v2.0.6b

### ISSUE THREAD

**Issue by ghost** [KryptoST/SRTranslatorGUI#15]
Hello. When I try to translate from English to Turkish, I am having "Translation timed out" error. This was not happening a day or two days ago. I was having it from time to time, but eventually it was translating. Right now, it stopped working completely.
![timed out](https://github.com/KryptoST/SRTranslatorGUI/assets/141356815/6036876d-0137-4a25-9810-54681f4056a8)

**Comment by pise77** [comment]
me too

**Comment by KryptoST** [comment]
I already solved the problem. It should have been resolved in v2.0.6b but one of the libraries was not updated.

**Comment by ghost** [comment]
> I already solved the problem. It should have been resolved in v2.0.6b but one of the libraries was not updated.

Thank you so much, it works now! 😊 But sometimes there are blank lines, is this because of DeepL?

**Comment by KevinSierraRojas** [comment]
@arlovibre While a solution is made you can actually spot when that specific problem appears and prevent wasting time to get a defective srt file. The real problem aren't the blank lines (If you get a few, you can just use DeepL to "manually" translate those lines), actually what is troublesome is that the lines get desynchronize.

You can kill the process at the moment you identify the problem.... Just check how much Memory is the "Geckodriver" procces usign, if you see that it's over a threshold (In my case the process always uses around 330 Mb, no matter how long is the srt file) close the window/s and restart the GUI.

No blank lines:
![image](https://github.com/KryptoST/SRTranslatorGUI/assets/129124101/0a08cd52-51fb-446c-96f7-088d4045d5b8)

Blank lines:
![image](https://github.com/KryptoST/SRTranslatorGUI/assets/129124101/94d5b30d-69fe-4ef1-bffc-61dbb274aa53)

This is not a real solution, but you can save time.

**Comment by ghost** [comment]
Thank you for your answer. I will keep this in mind. Best wishes.
