### ISSUE TITLE
Translator doesn't work

### ISSUE THREAD

**Issue by jordan1227** [KryptoST/SRTranslatorGUI#4]
Can't translate no matter how long I wait. I tried splitting the srt into several parts, but it still doesn't work.

**Comment by KryptoST** [comment]
what version of srt translator(python) do you have

**Comment by jordan1227** [comment]
> какая версия переводчика srt (python) у вас есть?

Никакой нет, кроме этой, что я установил. Должен ли я ещё что-то устанавливать?

**Comment by jordan1227** [comment]
> what version of srt translator(python) do you have

I don't have anything other than this version of the translator installed. Do I have to install anything else?

**Comment by KryptoST** [comment]
-https://github.com/sinedie/SRTranslator
- Firefox

**Comment by jordan1227** [comment]
Thanks. Should the GUI and this srttranslator be in the same directory?

**Comment by KryptoST** [comment]
you have to install python and then open the cmd and type pip install srtranslator
