### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mshjz** [KryptoST/SRTranslatorGUI#6]
I don't know anything, please ask how to make it work properly

**Comment by KryptoST** [comment]
You only need to have Firefox installed

**Comment by ghost** [comment]
> You only need to have Firefox installed

Hi. I could not start it using Firefox. Could you please help me? I literally do not know anything about coding stuff. Thanks.

**Comment by KryptoST** [comment]
> > You only need to have Firefox installed
> 
> Hi. I could not start it using Firefox. Could you please help me? I literally do not know anything about coding stuff. Thanks.

If you are using version 1.x this is necessary https://github.com/sinedie/SRTranslator
