### ISSUE TITLE
I press translate and nothing happend

### ISSUE THREAD

**Issue by Funkadelik** [KryptoST/SRTranslatorGUI#7]
![Screenshot_408](https://github.com/KryptoST/SRTranslatorGUI/assets/25404805/c1f5a384-cb4b-4faa-9680-8f84208483e8)

**Comment by KryptoST** [comment]
do you have this? https://github.com/sinedie/SRTranslator

**Comment by KryptoST** [comment]
If you don't want to install it, use the beta version.
