### ISSUE TITLE
new problem

### ISSUE THREAD

**Issue by pise77** [KryptoST/SRTranslatorGUI#8]
I'm using it well, but (en to kr)

It turns off when I'm working on multiple files, so I checked what's wrong.

The program truncates at 3000 characters, 

but deepl only translates 1500 characters.

As a result, srttranslator is stuck because it can't execute the clear command.

It would be nice if you could add a character limit. Thanks.

**Comment by KryptoST** [comment]
what version are you using?

**Comment by pise77** [comment]
test ver 2.03b, 2.02b, 1.1.2



2023년 7월 2일 (일) 오전 2:54, KryptoST ***@***.***>님이 작성:

**Comment by KryptoST** [comment]
I already found the problem is that they have changed the limit of the page

**Comment by pise77** [comment]
perfect.
