### ISSUE TITLE
Squares instead of Cyrillic

### ISSUE THREAD

**Issue by m1nuzz** [KryptoST/SRTranslatorGUI#9]
I was translating into Ukrainian, and after translation I got some squares 
![image](https://github.com/KryptoST/SRTranslatorGUI/assets/109736024/7e33c1fa-b2a0-487f-8203-67f77445de74)

**Comment by KryptoST** [comment]
I just checked and if it appears fine to me, it may be because where you opened the file it does not have the correct format.
![image](https://github.com/KryptoST/SRTranslatorGUI/assets/30755854/52e560d7-5c53-481b-b4ad-4170812fa6cc)
